#!/bin/sh

start() {
    printf 'Starting aesdsocket: '
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf 'Stopping aesdsocket: '
    start-stop-daemon -K -n aesdsocket >/dev/null
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start|stop)
        "$1";;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
